# Generated by Django 2.2.1 on 2019-05-03 12:38

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_example_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplepage',
            name='docs',
            field=wagtail.core.fields.StreamField([('doc', wagtail.documents.blocks.DocumentChooserBlock()), ('page', wagtail.core.blocks.PageChooserBlock())]),
        ),
    ]
