# Generated by Django 2.2.1 on 2019-05-03 13:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_pages_with_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplepage',
            name='content',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.RichTextBlock()), ('docs', wagtail.core.blocks.StreamBlock([('doc', wagtail.documents.blocks.DocumentChooserBlock()), ('image', wagtail.core.blocks.PageChooserBlock())]))], blank=True, null=True),
        ),
    ]
