# Generated by Django 2.2.1 on 2019-05-03 15:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_content_streamfield_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplepage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='examplepage',
            name='docs',
        ),
        migrations.RemoveField(
            model_name='examplepage',
            name='image',
        ),
        migrations.AlterField(
            model_name='examplepage',
            name='content',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.RichTextBlock()), ('docs', wagtail.core.blocks.StreamBlock([('doc', wagtail.documents.blocks.DocumentChooserBlock()), ('page', wagtail.core.blocks.PageChooserBlock())]))]),
        ),
    ]
